[package]
name = "ics-proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = {git = "https://github.com/actix/actix-web.git", tag="web-v4.0.0-beta.11"}
uuid = { version = "0.8.2", features = ["v4"] }
url = "2.2"
reqwest = { version = "0.11", features = ["blocking"] }
tera = "1.12.1"
dotenv = "0.15"

sqlx = { version = "0.5.9", features = [ "sqlite", "runtime-actix-rustls" ] }