[package]
name = "ics-proxy"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
uuid = { version = "0.8.2", features = ["v4"] }
reqwest = { version = "0.11", features = ["blocking"] }
tera = "1.12.1"