version: '3'
services:
  ics-proxy:
    container_name: ics-proxy
    image: ghcr.io/13hannes11/ics-proxy:latest
    env_file: .env
    ports:
     - "8080:8080"
    volumes:
     - database:/app/db
volumes:
  database:
