name: Test Workflow

on:
  workflow_call:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    container:
      image: rust:latest-slim
    steps:
      - uses: actions/checkout@v3

      - name: Install build debendencies
        run: |
          apt-get update
          apt-get install -y sqlite3 libsqlite3-dev build-essential pkg-config libssl-dev

      - name: "Cache cargo"
        id: cache-cargo
        uses: "actions/cache@v4"
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: "Install sqlx cli"
        run: "cargo install sqlx-cli"

      - name: Add .cargo/bin to PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Create database for sqlx
        run: |
          sqlx database create
          sqlx migrate run

      - name: Run build
        run: cargo build

      - name: Run tests
        run: cargo test --verbose
